CREATE TABLE fiveeighthouse
(
  id              INT(10) AUTO_INCREMENT PRIMARY KEY,
  onlyId          VARCHAR(100) UNIQUE not null,
  originalLink     VARCHAR(255),
  title            VARCHAR(100),
  publishDate      VARCHAR(100),
  price            VARCHAR(100),
  houseType        VARCHAR(100),
  quyu             VARCHAR(100),
  jiedao           VARCHAR(100),
  mprice            VARCHAR(100),
  area              VARCHAR(100),
  villageName      VARCHAR(100),
  houseAdress      VARCHAR(100),
  contactName      VARCHAR(100),
  phone            VARCHAR(100),
  decType          VARCHAR(100),
  houseCategory    VARCHAR(100),
  keepYear         VARCHAR(100),
  floor            VARCHAR(100),
  buildYear        VARCHAR(100),
  orientation      VARCHAR(100),
  description      VARCHAR(10000),
  imgUlr           TEXT,
  buildStructure   VARCHAR(100),
  houseSellingType VARCHAR(100),
  addDate          DATETIME,
  isDelete         INT(10),
  isUsed           INT(10)
);